local M = {}

---Get the persistent disabled config file path in ~/.config/nvim/lua/plugins/
---@return string
local function get_disabled_filepath()
  local config_dir = vim.fn.stdpath("config")
  return config_dir .. "/lua/plugins/perf_disabled.lua"
end

---Read the list of persistently disabled plugins from file
---@return table<string, boolean>
function M.get_persisted_disabled()
  local path = get_disabled_filepath()
  local disabled = {}
  local file = io.open(path, "r")
  if not file then
    return disabled
  end

  local content = file:read("*a")
  file:close()

  for name in content:gmatch('["\']([%w%-_%.]+)["\']%s*,%s*enabled%s*=%s*false') do
    disabled[name] = true
  end

  return disabled
end

---Persist the disabled plugins list to ~/.config/nvim/lua/plugins/perf_disabled.lua
---@param disabled_map table<string, boolean>
local function save_persisted_disabled(disabled_map)
  local path = get_disabled_filepath()
  local list = {}
  for name, is_disabled in pairs(disabled_map) do
    if is_disabled then
      table.insert(list, name)
    end
  end
  table.sort(list)

  if #list == 0 then
    -- Remove file if no plugins disabled
    os.remove(path)
    return
  end

  local lines = {
    "-- Auto-generated by nvim-perf-lens.nvim",
    "-- Contains plugins disabled on demand to optimize performance.",
    "return {",
  }

  for _, name in ipairs(list) do
    table.insert(lines, string.format('  { "%s", enabled = false },', name))
  end
  table.insert(lines, "}")
  table.insert(lines, "")

  local file = io.open(path, "w")
  if file then
    file:write(table.concat(lines, "\n"))
    file:close()
  end
end

---Get list of all plugins from Lazy.nvim or Neovim runtime
---@return table[]
function M.list_plugins()
  local list = {}
  local lazy_cfg = package.loaded["lazy.core.config"]
  local plugins = (lazy_cfg and lazy_cfg.plugins) or {}

  local persisted_disabled = M.get_persisted_disabled()

  for name, plug in pairs(plugins) do
    local is_loaded = plug._ and plug._.loaded ~= nil
    local is_enabled = plug.enabled ~= false and not persisted_disabled[name]
    local repo = plug[1] or name
    local lazy_type = plug.lazy and "lazy" or "eager"
    local events = plug.event or plug.cmd or plug.ft or plug.keys or nil

    table.insert(list, {
      name = name,
      repo = repo,
      enabled = is_enabled,
      loaded = is_loaded,
      lazy = plug.lazy == true,
      lazy_type = lazy_type,
      events = events,
      raw = plug,
    })
  end

  table.sort(list, function(a, b)
    if a.enabled ~= b.enabled then
      return a.enabled and not b.enabled
    end
    if a.loaded ~= b.loaded then
      return a.loaded and not b.loaded
    end
    return a.name < b.name
  end)

  return list
end

---Disable a plugin dynamically and optionally persist across restarts
---@param plugin_name string
---@param persist? boolean (default true)
---@return boolean success, string message
function M.disable_plugin(plugin_name, persist)
  if persist == nil then
    persist = true
  end

  local lazy_cfg = package.loaded["lazy.core.config"]
  if lazy_cfg and lazy_cfg.plugins and lazy_cfg.plugins[plugin_name] then
    lazy_cfg.plugins[plugin_name].enabled = false
  end

  if persist then
    local disabled_map = M.get_persisted_disabled()
    disabled_map[plugin_name] = true
    save_persisted_disabled(disabled_map)
  end

  return true, string.format("Plugin '%s' disabled%s.", plugin_name, persist and " and persisted in perf_disabled.lua" or " (runtime only)")
end

---Enable a plugin and remove from disabled list
---@param plugin_name string
---@param persist? boolean (default true)
---@return boolean success, string message
function M.enable_plugin(plugin_name, persist)
  if persist == nil then
    persist = true
  end

  local lazy_cfg = package.loaded["lazy.core.config"]
  if lazy_cfg and lazy_cfg.plugins and lazy_cfg.plugins[plugin_name] then
    lazy_cfg.plugins[plugin_name].enabled = true
  end

  if persist then
    local disabled_map = M.get_persisted_disabled()
    disabled_map[plugin_name] = nil
    save_persisted_disabled(disabled_map)
  end

  return true, string.format("Plugin '%s' re-enabled%s.", plugin_name, persist and " and saved" or "")
end

---Toggle a plugin's enabled status
---@param plugin_name string
---@param persist? boolean (default true)
---@return boolean new_enabled_state, string message
function M.toggle_plugin(plugin_name, persist)
  local disabled_map = M.get_persisted_disabled()
  local is_disabled = disabled_map[plugin_name] == true

  local lazy_cfg = package.loaded["lazy.core.config"]
  if lazy_cfg and lazy_cfg.plugins and lazy_cfg.plugins[plugin_name] then
    if lazy_cfg.plugins[plugin_name].enabled == false then
      is_disabled = true
    end
  end

  if is_disabled then
    M.enable_plugin(plugin_name, persist)
    return true, string.format("Enabled %s", plugin_name)
  else
    M.disable_plugin(plugin_name, persist)
    return false, string.format("Disabled %s", plugin_name)
  end
end

return M
