local config = require("cmd_cockpit.config")

local M = {}

---@class KeymapOverride
---@field mode string
---@field old_lhs string
---@field new_lhs string
---@field rhs string
---@field desc string
---@field silent boolean
---@field noremap boolean

---@type table<string, KeymapOverride>
M.overrides = {}

---Get storage file for overrides
---@return string
local function get_overrides_state_file()
  local dir = config.options.storage_dir or (vim.fn.stdpath("state") .. "/cmd-cockpit")
  if vim.fn.isdirectory(dir) == 0 then
    vim.fn.mkdir(dir, "p")
  end
  return dir .. "/overrides.json"
end

---Apply a single keymap override
---@param mode string
---@param old_lhs string
---@param new_lhs string
---@param rhs? string
---@param desc? string
---@return boolean, string
function M.set_override(mode, old_lhs, new_lhs, rhs, desc)
  local m = mode or "n"
  local target_rhs = rhs

  -- If RHS was not explicitly provided, look up the existing mapping's RHS
  if not target_rhs or target_rhs == "" then
    local maps = vim.api.nvim_get_keymap(m)
    for _, map in ipairs(maps) do
      if map.lhs == old_lhs then
        target_rhs = map.rhs
        desc = desc or map.desc
        break
      end
    end
  end

  if not target_rhs or target_rhs == "" then
    return false, string.format("Could not resolve action for '%s'", old_lhs)
  end

  -- Unmap old key if different
  if old_lhs ~= new_lhs then
    pcall(vim.keymap.del, m, old_lhs)
  end

  -- Apply new keymap
  vim.keymap.set(m, new_lhs, target_rhs, {
    silent = true,
    noremap = true,
    desc = desc or string.format("Overridden from %s", old_lhs),
  })

  local key = string.format("%s:%s", m, new_lhs)
  M.overrides[key] = {
    mode = m,
    old_lhs = old_lhs,
    new_lhs = new_lhs,
    rhs = target_rhs,
    desc = desc or "",
    silent = true,
    noremap = true,
  }

  M.save()
  return true, string.format("Remapped [%s] '%s' -> '%s'", m, old_lhs, new_lhs)
end

---Remove an override and restore original mapping if known
---@param mode string
---@param lhs string
---@return boolean
function M.remove_override(mode, lhs)
  local key = string.format("%s:%s", mode, lhs)
  local ov = M.overrides[key]
  if ov then
    pcall(vim.keymap.del, mode, lhs)
    -- Restore original
    if ov.old_lhs and ov.rhs and ov.old_lhs ~= lhs then
      vim.keymap.set(mode, ov.old_lhs, ov.rhs, {
        silent = ov.silent,
        noremap = ov.noremap,
        desc = ov.desc,
      })
    end
    M.overrides[key] = nil
    M.save()
    return true
  end
  return false
end

---Reset all overrides
function M.reset_all()
  for _, ov in pairs(M.overrides) do
    pcall(vim.keymap.del, ov.mode, ov.new_lhs)
    if ov.old_lhs ~= ov.new_lhs and ov.rhs then
      vim.keymap.set(ov.mode, ov.old_lhs, ov.rhs, { desc = ov.desc })
    end
  end
  M.overrides = {}
  M.save()
end

---Save overrides to state file
function M.save()
  local file = get_overrides_state_file()
  local encoded = vim.fn.json_encode(M.overrides)
  local f = io.open(file, "w")
  if f then
    f:write(encoded)
    f:close()
  end
end

---Load and apply overrides from state file
function M.load_and_apply()
  local file = get_overrides_state_file()
  local f = io.open(file, "r")
  if not f then return end
  local content = f:read("*a")
  f:close()

  if content and content ~= "" then
    local ok, data = pcall(vim.fn.json_decode, content)
    if ok and type(data) == "table" then
      M.overrides = data
      for _, ov in pairs(M.overrides) do
        if ov.rhs and ov.rhs ~= "" and ov.new_lhs and ov.new_lhs ~= "" then
          vim.keymap.set(ov.mode, ov.new_lhs, ov.rhs, {
            silent = ov.silent,
            noremap = ov.noremap,
            desc = ov.desc ~= "" and ov.desc or nil,
          })
        end
      end
    end
  end
end

---Export active overrides as a standalone Lua module
---@param target_file? string
---@return boolean, string
function M.export_lua(target_file)
  local dest = target_file or config.options.overrides_file
  local parent = vim.fn.fnamemodify(dest, ":h")
  if vim.fn.isdirectory(parent) == 0 then
    vim.fn.mkdir(parent, "p")
  end

  local lines = {
    "-- Generated by cmd-cockpit.nvim Keymap Override Manager",
    "-- Add this file to your Neovim config (e.g. require('config.keymap_overrides'))",
    "",
    "local M = {}",
    "",
    "function M.setup()",
    "  local map = vim.keymap.set",
    "",
  }

  local count = 0
  for _, ov in pairs(M.overrides) do
    count = count + 1
    local line = string.format(
      '  map("%s", "%s", %s, { desc = "%s" }) -- Replaced %s',
      ov.mode,
      ov.new_lhs,
      (ov.rhs:match('^<[cC]md>') or ov.rhs:match('^:')) and string.format('"%s"', ov.rhs) or string.format('"%s"', ov.rhs),
      ov.desc:gsub('"', '\\"'),
      ov.old_lhs
    )
    table.insert(lines, line)
  end

  table.insert(lines, "")
  table.insert(lines, "end")
  table.insert(lines, "")
  table.insert(lines, "return M")

  local f = io.open(dest, "w")
  if not f then
    return false, string.format("Failed to write to '%s'", dest)
  end
  f:write(table.concat(lines, "\n"))
  f:close()

  return true, string.format("Exported %d overrides to '%s'", count, dest)
end

return M
